ALTER TABLE KS.StateVectors_DE435 DROP CONSTRAINT FK_StateVectors_DE435_TimeID;
ALTER TABLE KS.StateVectors_DE435 DROP CONSTRAINT FK_StateVectors_DE435_BodyID;
ALTER TABLE KS.StateVectors_DE435 engine='aria' transactional=0;

ALTER TABLE KS.StateVectors_DE435 ADD CONSTRAINT FK_StateVectors_DE435_TimeID FOREIGN KEY (TimeID) REFERENCES KS.IntegrationTime(TimeID);
ALTER TABLE KS.StateVectors_DE435 ADD CONSTRAINT FK_StateVectors_DE435_BodyID FOREIGN KEY (BodyID) REFERENCES KS.Body(BodyID);